apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: devenvironments_api1
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: http://api2:80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: api1
spec:
  selector:
    app.kubernetes.io/name: api1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80