apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: devenvironments_api1
        ports:
        - containerPort: 80
        env:
        - name: API__URL
          value: http://api2
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: api1
spec:
  type: ClusterIP # Optional field (default)
  selector: 
    app: api1
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80