apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  labels:
    app: api1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api1
  template:
    metadata:
      labels:
        app: api1
    spec:
      containers:
      - name: api1
        image: devenvironments_api1
        ports:
        - containerPort: 80
        env:
        - name: API__URL
          value: http://api2:80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: api1
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: api1