apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello

resources:
- ./deployment.yml

images:
- name: devenvironments_api1
  newTag: "latest"

replacements:
  - source:
      kind: Deployment
      name: api1
      fieldPath: metadata.annotations.app-prefix
    targets:
      - select:
          kind: Deployment
          name: api1
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=test].value