services:
  api1:
    build: 
      context: .
      dockerfile: ./API/Dockerfile
    container_name: api1
    environment:
      - API__URL=http://api2:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 81:80
  api2:
    build:
      context: .
      dockerfile: ./API2/Dockerfile
    container_name: api2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development