apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-environments
  labels:
    app: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
      - name: api2
        image: devenvironments_api2
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
