apiVersion: apps/v1
kind: Deployment
metadata:
  name: shpod
  namespace: dev-environments
  labels:
    app: shpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shpod
  template:
    metadata:
      labels:
        app: shpod
    spec:
      containers:
      - name: shpod
        image: jpetazzo/shpod
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: shpod
  namespace: dev-environments
spec:
  selector:
    app.kubernetes.io/name: shpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80