apiVersion: apps/v1
kind: Deployment
metadata:
  name: api3
  labels:
    app: api3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api3
  template:
    metadata:
      labels:
        app: api3
    spec:
      containers:
      - name: api3
        image: devenvironments_api3
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: api3
spec:
  selector:
    app.kubernetes.io/name: api3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80