apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api1-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: dev-environment1
      - namespace: dev-environment2
  template:
    metadata:
      name: '{{namespace}}-api1'
    spec:
      project: default
      source:
        repoURL: https://github.com/santanaguy/devEnvironments.git
        targetRevision: HEAD
        path: argo/api1/base
      destination:
        namespace: '{{namespace}}'
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true