apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api2-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: mc
      - namespace: as
  template:
    metadata:
      name: '{{namespace}}-api2'
    spec:
      project: default
      source:
        repoURL: https://github.com/santanaguy/devEnvironments.git
        targetRevision: HEAD
        path: argo/api2/base
      destination:
        namespace: '{{namespace}}'
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true